// build_info.cpp is generated by the build system using gen_build_info_cpp.py

#pragma once

namespace hg {

const char *get_version_string();
const char *get_build_sha();

const char *get_host_string();
const char *get_target_string();

} // namespace hg
